"""Soccer mock data for development and testing."""
from typing import Dict, List, Any

# Soccer games mock data
# Key format: "{date}_soccer" (e.g., "20251118_soccer")
# state: "f" = finished, "b" = before/scheduled, "i" = in-progress
MOCK_SOCCER_GAMES: Dict[str, List[Dict[str, Any]]] = {
    "20251118_soccer": [
        # 종료된 경기 - MOCK_SOCCER_PLAYER_STATS와 연동됨
        {
            "game_id": "MOCK_SOCCER_001",
            "league_id": "OT22187",
            "league_name": "UEFA챔피언스리그",
            "match_date": "20251118",
            "match_time": "04:00",
            "home_team_id": "OT21259",
            "away_team_id": "OT22253",
            "home_team_name": "대한민국",
            "away_team_name": "일본",
            "home_score": 3,
            "away_score": 1,
            "state": "f",
            "arena_name": "서울월드컵경기장",
        },
        # 진행중인 경기
        {
            "game_id": "MOCK_SOCCER_002",
            "league_id": "OT21306",
            "league_name": "EPL",
            "match_date": "20251118",
            "match_time": "21:00",
            "home_team_id": "OT2532",
            "away_team_id": "OT2524",
            "home_team_name": "토트넘",
            "away_team_name": "맨체스터 시티",
            "home_score": 2,
            "away_score": 1,
            "state": "i",
            "arena_name": "토트넘 홋스퍼 스타디움",
        },
        # 예정된 경기
        {
            "game_id": "MOCK_SOCCER_003",
            "league_id": "OT21255",
            "league_name": "K리그1",
            "match_date": "20251118",
            "match_time": "19:00",
            "home_team_id": "OT21260",
            "away_team_id": "OT21261",
            "home_team_name": "울산 현대",
            "away_team_name": "전북 현대",
            "home_score": 0,
            "away_score": 0,
            "state": "b",
            "arena_name": "울산문수축구경기장",
        },
    ],
}

# Soccer team stats mock data
# Key: game_id, Value: [home_team_stats, away_team_stats]
MOCK_SOCCER_TEAM_STATS: Dict[str, List[Dict[str, Any]]] = {
    # MOCK_SOCCER_001: 대한민국 3 - 1 일본 (종료)
    "MOCK_SOCCER_001": [
        {
            # 홈팀 (대한민국)
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            # 점유율
            "possessionPercentage": 58,
            # 슈팅
            "totalScoringAtt": 18,
            "ontargetScoringAtt": 9,
            "shotOffTarget": 6,
            "blockedScoringAtt": 3,
            "attemptsIbox": 12,
            "attemptsObox": 6,
            # 득점
            "goals": 3,
            "goalsIbox": 2,
            "goalsObox": 1,
            "firstHalfGoals": 2,
            # 패스
            "totalPass": 520,
            "accuratePass": 452,
            "totalFinalThirdPasses": 85,
            "successfulFinalThirdPasses": 68,
            # 크로스
            "totalCross": 18,
            "accurateCross": 7,
            # 수비
            "totalTackle": 15,
            "wonTackle": 10,
            "interception": 12,
            "totalClearance": 8,
            # 듀얼
            "duelWon": 52,
            "duelLost": 38,
            "aerialWon": 15,
            "aerialLost": 10,
            # 파울/카드
            "fkFoulLost": 10,
            "fkFoulWon": 14,
            "totalYellowCard": 1,
            # 코너/오프사이드
            "wonCorners": 7,
            "totalOffside": 2,
            # 골키퍼
            "saves": 4,
            # 터치
            "touches": 620,
            "touchesInOppBox": 28,
        },
        {
            # 원정팀 (일본)
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            # 점유율
            "possessionPercentage": 42,
            # 슈팅
            "totalScoringAtt": 12,
            "ontargetScoringAtt": 5,
            "shotOffTarget": 5,
            "blockedScoringAtt": 2,
            "attemptsIbox": 7,
            "attemptsObox": 5,
            # 득점
            "goals": 1,
            "goalsIbox": 1,
            "goalsObox": 0,
            "firstHalfGoals": 0,
            # 패스
            "totalPass": 380,
            "accuratePass": 312,
            "totalFinalThirdPasses": 52,
            "successfulFinalThirdPasses": 38,
            # 크로스
            "totalCross": 12,
            "accurateCross": 4,
            # 수비
            "totalTackle": 18,
            "wonTackle": 12,
            "interception": 8,
            "totalClearance": 15,
            # 듀얼
            "duelWon": 38,
            "duelLost": 52,
            "aerialWon": 10,
            "aerialLost": 15,
            # 파울/카드
            "fkFoulLost": 14,
            "fkFoulWon": 10,
            "totalYellowCard": 2,
            # 코너/오프사이드
            "wonCorners": 4,
            "totalOffside": 3,
            # 골키퍼
            "saves": 6,
            # 터치
            "touches": 480,
            "touchesInOppBox": 18,
        },
    ],
    # MOCK_SOCCER_002: 토트넘 2 - 1 맨시티 (진행중)
    "MOCK_SOCCER_002": [
        {
            # 홈팀 (토트넘)
            "GAME_ID": "MOCK_SOCCER_002",
            "TEAM_ID": "OT2532",
            "HOME_AWAY": "home",
            "possessionPercentage": 45,
            "totalScoringAtt": 10,
            "ontargetScoringAtt": 5,
            "totalPass": 280,
            "accuratePass": 235,
            "fkFoulLost": 8,
            "wonCorners": 4,
            "totalOffside": 1,
            "totalYellowCard": 1,
            "goals": 2,
            "saves": 5,
        },
        {
            # 원정팀 (맨체스터 시티)
            "GAME_ID": "MOCK_SOCCER_002",
            "TEAM_ID": "OT2524",
            "HOME_AWAY": "away",
            "possessionPercentage": 55,
            "totalScoringAtt": 14,
            "ontargetScoringAtt": 6,
            "totalPass": 350,
            "accuratePass": 312,
            "fkFoulLost": 10,
            "wonCorners": 6,
            "totalOffside": 2,
            "totalYellowCard": 0,
            "goals": 1,
            "saves": 3,
        },
    ],
}

# Soccer player stats mock data
# Key: game_id, Value: list of player stats
# formationPlace: 1=GK, 2-5=DF, 6-8=MF(센터), 3=LB, 4=CB, 7=LW, 9=ST, 10=CAM, 11=RW
MOCK_SOCCER_PLAYER_STATS: Dict[str, List[Dict[str, Any]]] = {
    "MOCK_SOCCER_001": [
        # Home Team (OT21259) - 선발 11명
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP001",
            "PLAYER_NAME": "김승규",
            "BACK_NO": "1",
            "formationPlace": "1",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "0",
            "ontargetScoringAtt": "0",
            "totalPass": "28",
            "accuratePass": "22",
            "totalTackle": "0",
            "interception": "0",
            "fouls": "0",
            "yellowCard": "0",
            "saves": "4",
            "goalsConceded": "1",
            "Touches": "35",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP002",
            "PLAYER_NAME": "김민재",
            "BACK_NO": "3",
            "formationPlace": "4",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "1",
            "ontargetScoringAtt": "0",
            "totalPass": "65",
            "accuratePass": "58",
            "totalTackle": "3",
            "interception": "2",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "78",
            "aerialWon": "4",
            "totalClearance": "5",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP003",
            "PLAYER_NAME": "김영권",
            "BACK_NO": "4",
            "formationPlace": "5",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "0",
            "ontargetScoringAtt": "0",
            "totalPass": "58",
            "accuratePass": "52",
            "totalTackle": "2",
            "interception": "3",
            "fouls": "2",
            "yellowCard": "1",
            "Touches": "70",
            "aerialWon": "3",
            "totalClearance": "4",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP004",
            "PLAYER_NAME": "김진수",
            "BACK_NO": "15",
            "formationPlace": "3",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "1",
            "totalScoringAtt": "1",
            "ontargetScoringAtt": "0",
            "totalPass": "45",
            "accuratePass": "38",
            "totalTackle": "2",
            "interception": "1",
            "totalCross": "5",
            "accurateCross": "2",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "62",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP005",
            "PLAYER_NAME": "윤종규",
            "BACK_NO": "2",
            "formationPlace": "2",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "0",
            "ontargetScoringAtt": "0",
            "totalPass": "42",
            "accuratePass": "36",
            "totalTackle": "4",
            "interception": "2",
            "totalCross": "3",
            "accurateCross": "1",
            "fouls": "0",
            "yellowCard": "0",
            "Touches": "55",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP006",
            "PLAYER_NAME": "황인범",
            "BACK_NO": "6",
            "formationPlace": "6",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "2",
            "ontargetScoringAtt": "1",
            "totalPass": "72",
            "accuratePass": "65",
            "totalTackle": "3",
            "interception": "4",
            "fouls": "2",
            "yellowCard": "0",
            "Touches": "88",
            "ballRecovery": "5",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP007",
            "PLAYER_NAME": "정우영",
            "BACK_NO": "8",
            "formationPlace": "8",
            "gameStarted": "1",
            "minsPlayed": "78",
            "Goals": "0",
            "goalAssist": "1",
            "totalScoringAtt": "3",
            "ontargetScoringAtt": "1",
            "totalPass": "48",
            "accuratePass": "42",
            "totalTackle": "1",
            "interception": "1",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "65",
            "bigChanceCreated": "1",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP008",
            "PLAYER_NAME": "이강인",
            "BACK_NO": "10",
            "formationPlace": "10",
            "gameStarted": "1",
            "minsPlayed": "85",
            "Goals": "1",
            "goalAssist": "1",
            "totalScoringAtt": "4",
            "ontargetScoringAtt": "2",
            "totalPass": "38",
            "accuratePass": "30",
            "totalTackle": "0",
            "interception": "0",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "58",
            "bigChanceCreated": "2",
            "totalAttAssist": "3",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP009",
            "PLAYER_NAME": "손흥민",
            "BACK_NO": "7",
            "formationPlace": "7",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "1",
            "goalAssist": "0",
            "totalScoringAtt": "5",
            "ontargetScoringAtt": "3",
            "totalPass": "25",
            "accuratePass": "18",
            "totalTackle": "1",
            "interception": "0",
            "fouls": "0",
            "yellowCard": "0",
            "Touches": "48",
            "progressiveCarries": "6",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP010",
            "PLAYER_NAME": "황희찬",
            "BACK_NO": "11",
            "formationPlace": "11",
            "gameStarted": "1",
            "minsPlayed": "70",
            "Goals": "0",
            "goalAssist": "1",
            "totalScoringAtt": "2",
            "ontargetScoringAtt": "1",
            "totalPass": "18",
            "accuratePass": "14",
            "totalTackle": "2",
            "interception": "0",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "35",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP011",
            "PLAYER_NAME": "조규성",
            "BACK_NO": "9",
            "formationPlace": "9",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "1",
            "goalAssist": "0",
            "totalScoringAtt": "6",
            "ontargetScoringAtt": "3",
            "totalPass": "15",
            "accuratePass": "10",
            "totalTackle": "0",
            "interception": "0",
            "fouls": "2",
            "yellowCard": "1",
            "Touches": "32",
            "aerialWon": "5",
        },
        # Home Team - 교체 선수
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP012",
            "PLAYER_NAME": "이재성",
            "BACK_NO": "14",
            "formationPlace": "0",
            "gameStarted": "0",
            "minsPlayed": "20",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "1",
            "ontargetScoringAtt": "0",
            "totalPass": "12",
            "accuratePass": "10",
            "totalTackle": "1",
            "interception": "0",
            "fouls": "0",
            "yellowCard": "0",
            "Touches": "18",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT21259",
            "HOME_AWAY": "home",
            "PLAYER_ID": "HP013",
            "PLAYER_NAME": "백승호",
            "BACK_NO": "16",
            "formationPlace": "0",
            "gameStarted": "0",
            "minsPlayed": "12",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "0",
            "ontargetScoringAtt": "0",
            "totalPass": "8",
            "accuratePass": "7",
            "totalTackle": "0",
            "interception": "1",
            "fouls": "0",
            "yellowCard": "0",
            "Touches": "10",
        },
        # Away Team (OT22253) - 선발 11명
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP001",
            "PLAYER_NAME": "조현우",
            "BACK_NO": "21",
            "formationPlace": "1",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "0",
            "ontargetScoringAtt": "0",
            "totalPass": "32",
            "accuratePass": "25",
            "totalTackle": "0",
            "interception": "0",
            "fouls": "0",
            "yellowCard": "0",
            "saves": "6",
            "goalsConceded": "3",
            "Touches": "42",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP002",
            "PLAYER_NAME": "홍철",
            "BACK_NO": "2",
            "formationPlace": "2",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "1",
            "ontargetScoringAtt": "0",
            "totalPass": "38",
            "accuratePass": "32",
            "totalTackle": "3",
            "interception": "1",
            "totalCross": "4",
            "fouls": "2",
            "yellowCard": "1",
            "Touches": "52",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP003",
            "PLAYER_NAME": "권경원",
            "BACK_NO": "4",
            "formationPlace": "4",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "0",
            "ontargetScoringAtt": "0",
            "totalPass": "55",
            "accuratePass": "48",
            "totalTackle": "2",
            "interception": "2",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "65",
            "aerialWon": "3",
            "totalClearance": "4",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP004",
            "PLAYER_NAME": "박지수",
            "BACK_NO": "5",
            "formationPlace": "5",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "1",
            "ontargetScoringAtt": "1",
            "totalPass": "52",
            "accuratePass": "45",
            "totalTackle": "1",
            "interception": "3",
            "fouls": "0",
            "yellowCard": "0",
            "Touches": "62",
            "aerialWon": "2",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP005",
            "PLAYER_NAME": "이용",
            "BACK_NO": "3",
            "formationPlace": "3",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "1",
            "totalScoringAtt": "0",
            "ontargetScoringAtt": "0",
            "totalPass": "40",
            "accuratePass": "35",
            "totalTackle": "2",
            "interception": "1",
            "totalCross": "6",
            "accurateCross": "2",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "58",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP006",
            "PLAYER_NAME": "손준호",
            "BACK_NO": "6",
            "formationPlace": "6",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "1",
            "goalAssist": "0",
            "totalScoringAtt": "3",
            "ontargetScoringAtt": "2",
            "totalPass": "62",
            "accuratePass": "55",
            "totalTackle": "4",
            "interception": "3",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "78",
            "ballRecovery": "4",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP007",
            "PLAYER_NAME": "이재성",
            "BACK_NO": "8",
            "formationPlace": "8",
            "gameStarted": "1",
            "minsPlayed": "75",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "2",
            "ontargetScoringAtt": "0",
            "totalPass": "42",
            "accuratePass": "36",
            "totalTackle": "2",
            "interception": "2",
            "fouls": "2",
            "yellowCard": "0",
            "Touches": "55",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP008",
            "PLAYER_NAME": "권창훈",
            "BACK_NO": "10",
            "formationPlace": "10",
            "gameStarted": "1",
            "minsPlayed": "80",
            "Goals": "0",
            "goalAssist": "1",
            "totalScoringAtt": "2",
            "ontargetScoringAtt": "1",
            "totalPass": "35",
            "accuratePass": "28",
            "totalTackle": "1",
            "interception": "0",
            "fouls": "0",
            "yellowCard": "0",
            "Touches": "48",
            "bigChanceCreated": "1",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP009",
            "PLAYER_NAME": "나상호",
            "BACK_NO": "7",
            "formationPlace": "7",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "3",
            "ontargetScoringAtt": "1",
            "totalPass": "22",
            "accuratePass": "16",
            "totalTackle": "1",
            "interception": "0",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "40",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP010",
            "PLAYER_NAME": "문선민",
            "BACK_NO": "11",
            "formationPlace": "11",
            "gameStarted": "1",
            "minsPlayed": "65",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "1",
            "ontargetScoringAtt": "0",
            "totalPass": "15",
            "accuratePass": "12",
            "totalTackle": "1",
            "interception": "1",
            "fouls": "0",
            "yellowCard": "0",
            "Touches": "28",
        },
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP011",
            "PLAYER_NAME": "주민규",
            "BACK_NO": "9",
            "formationPlace": "9",
            "gameStarted": "1",
            "minsPlayed": "90",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "4",
            "ontargetScoringAtt": "2",
            "totalPass": "12",
            "accuratePass": "8",
            "totalTackle": "0",
            "interception": "0",
            "fouls": "3",
            "yellowCard": "1",
            "Touches": "28",
            "aerialWon": "4",
        },
        # Away Team - 교체 선수
        {
            "GAME_ID": "MOCK_SOCCER_001",
            "TEAM_ID": "OT22253",
            "HOME_AWAY": "away",
            "PLAYER_ID": "AP012",
            "PLAYER_NAME": "엄원상",
            "BACK_NO": "17",
            "formationPlace": "0",
            "gameStarted": "0",
            "minsPlayed": "25",
            "Goals": "0",
            "goalAssist": "0",
            "totalScoringAtt": "1",
            "ontargetScoringAtt": "1",
            "totalPass": "10",
            "accuratePass": "8",
            "totalTackle": "0",
            "interception": "0",
            "fouls": "1",
            "yellowCard": "0",
            "Touches": "15",
        },
    ],
}

# Soccer lineup mock data
MOCK_SOCCER_LINEUP: Dict[str, List[Dict[str, Any]]] = {
    # Test data for development - extend as needed
}


# Soccer team rank mock data (league standings)
# Key format: "{league_id}_{season_id}"
MOCK_SOCCER_TEAM_RANK: Dict[str, List[Dict[str, Any]]] = {
    # UEFA Champions League 2025 standings
    "OT22187_2025": [
        {
            "RANK": 1,
            "TEAM_ID": "OT2898",
            "GROUP_SC": "리그 페이즈",
            "GAME_CN": "6",
            "ALL_WP": "16",
            "ALL_W_CN": "5",
            "ALL_D_CN": "1",
            "ALL_L_CN": "0",
            "ALL_R_SCORE": "11",
            "ALL_L_SCORE": "5",
            "GROUP_TYPE": "88647",
            "GROUP_NAME": "",
        },
        {
            "RANK": 2,
            "TEAM_ID": "OT23113",
            "GROUP_SC": "리그 페이즈",
            "GAME_CN": "6",
            "ALL_WP": "14",
            "ALL_W_CN": "4",
            "ALL_D_CN": "2",
            "ALL_L_CN": "0",
            "ALL_R_SCORE": "9",
            "ALL_L_SCORE": "2",
            "GROUP_TYPE": "88647",
            "GROUP_NAME": "",
        },
        {
            "RANK": 3,
            "TEAM_ID": "OT21042",
            "GROUP_SC": "리그 페이즈",
            "GAME_CN": "6",
            "ALL_WP": "13",
            "ALL_W_CN": "4",
            "ALL_D_CN": "1",
            "ALL_L_CN": "1",
            "ALL_R_SCORE": "14",
            "ALL_L_SCORE": "7",
            "GROUP_TYPE": "88647",
            "GROUP_NAME": "",
        },
        {
            "RANK": 4,
            "TEAM_ID": "OT2532",
            "GROUP_SC": "리그 페이즈",
            "GAME_CN": "6",
            "ALL_WP": "13",
            "ALL_W_CN": "4",
            "ALL_D_CN": "1",
            "ALL_L_CN": "1",
            "ALL_R_SCORE": "10",
            "ALL_L_SCORE": "3",
            "GROUP_TYPE": "88647",
            "GROUP_NAME": "",
        },
        {
            "RANK": 5,
            "TEAM_ID": "OT22054",
            "GROUP_SC": "리그 페이즈",
            "GAME_CN": "6",
            "ALL_WP": "13",
            "ALL_W_CN": "4",
            "ALL_D_CN": "1",
            "ALL_L_CN": "1",
            "ALL_R_SCORE": "13",
            "ALL_L_SCORE": "7",
            "GROUP_TYPE": "88647",
            "GROUP_NAME": "",
        },
        {
            "RANK": 6,
            "TEAM_ID": "OT22254",
            "GROUP_SC": "리그 페이즈",
            "GAME_CN": "6",
            "ALL_WP": "13",
            "ALL_W_CN": "4",
            "ALL_D_CN": "1",
            "ALL_L_CN": "1",
            "ALL_R_SCORE": "10",
            "ALL_L_SCORE": "5",
            "GROUP_TYPE": "88647",
            "GROUP_NAME": "",
        },
        {
            "RANK": 7,
            "TEAM_ID": "OT2977",
            "GROUP_SC": "리그 페이즈",
            "GAME_CN": "6",
            "ALL_WP": "13",
            "ALL_W_CN": "4",
            "ALL_D_CN": "1",
            "ALL_L_CN": "1",
            "ALL_R_SCORE": "7",
            "ALL_L_SCORE": "3",
            "GROUP_TYPE": "88647",
            "GROUP_NAME": "",
        },
        {
            "RANK": 8,
            "TEAM_ID": "OT2524",
            "GROUP_SC": "리그 페이즈",
            "GAME_CN": "6",
            "ALL_WP": "12",
            "ALL_W_CN": "3",
            "ALL_D_CN": "3",
            "ALL_L_CN": "0",
            "ALL_R_SCORE": "7",
            "ALL_L_SCORE": "1",
            "GROUP_TYPE": "88647",
            "GROUP_NAME": "",
        },
    ],
}


# Soccer player season stats mock data
# Key format: "{league_id}_{season_id}_{team_id}_{player_id}"
MOCK_SOCCER_PLAYER_SEASON_STATS: Dict[str, List[Dict[str, Any]]] = {
    # Example: 손흥민 시즌 스탯
    "OT22187_2025_OT22253_OT253039": [
        {
            # 패스 관련
            "accurateBackZonePass": 7,
            "accurateFlickOn": 1,
            "accurateFwdZonePass": 9,
            "accurateLayoffs": 3,
            "accuratePass": 16,
            "backwardPass": 5,
            "blockedPass": 1,
            "fwdPass": 6,
            "headPass": 3,
            "leftsidePass": 6,
            "rightsidePass": 2,
            "longPassOwnToOpp": 1,
            "longPassOwnToOppSuccess": 1,
            "openPlayPass": 18,
            "passesLeft": 1,
            "passesRight": 4,
            "successfulFinalThirdPasses": 4,
            "successfulOpenPlayPass": 15,
            "successfulPutThrough": 1,
            "totalBackZonePass": 7,
            "totalChippedPass": 1,
            "totalFinalThirdPasses": 7,
            "totalFlickOn": 2,
            "totalFwdZonePass": 12,
            "totalLayoffs": 3,
            "totalPass": 19,
            "totalThroughBall": 1,
            "putThrough": 1,

            # 슈팅/득점 관련
            "attBxCentre": 2,
            "attemptsIbox": 2,
            "attGoalHighRight": 1,
            "attHdMiss": 1,
            "attHdTotal": 1,
            "attIboxGoal": 1,
            "attIboxMiss": 1,
            "attLfGoal": 1,
            "attLfTotal": 1,
            "attMissLeft": 1,
            "attOpenplay": 1,
            "bigChanceMissed": 1,
            "Goals": 2,
            "goalsOpenplay": 1,
            "ontargetScoringAtt": 1,
            "shotOffTarget": 1,
            "totalScoringAtt": 2,
            "winningGoal": 0,

            # 수비/실점 관련
            "attemptsConcededIbox": 6,
            "attemptsConcededObox": 3,
            "goalsConceded": 1,
            "goalsConcededIbox": 1,

            # 볼 소유/드리블 관련
            "ballRecovery": 2,
            "carries": 11,
            "dispossessed": 2,
            "finalThirdEntries": 2,
            "penAreaEntries": 1,
            "possLostAll": 7,
            "possLostCtrl": 7,
            "possWonDef3rd": 1,
            "possWonMid3rd": 1,
            "progressiveCarries": 3,
            "Touches": 53,
            "touchesInFinalThird": 12,
            "touchesInOppBox": 6,
            "turnover": 2,
            "unsuccessfulTouch": 2,

            # 대인 플레이
            "challengeLost": 1,
            "duelLost": 3,
            "duelWon": 2,
            "timesTackled": 2,
            "totalContest": 1,
            "totalTackle": 1,
            "wonContest": 1,

            # 출전 관련
            "formationPlace": 0,
            "minsPlayed": 56,
            "totalSubOn": 3,
        },
    ],
    # Example: 이강인 시즌 스탯
    "OT22187_2025_OT21259_OT253040": [
        {
            # 패스 관련
            "accurateBackZonePass": 12,
            "accurateFlickOn": 3,
            "accurateFwdZonePass": 18,
            "accurateLayoffs": 5,
            "accuratePass": 45,
            "backwardPass": 8,
            "blockedPass": 2,
            "fwdPass": 15,
            "headPass": 2,
            "leftsidePass": 10,
            "rightsidePass": 8,
            "longPassOwnToOpp": 3,
            "longPassOwnToOppSuccess": 2,
            "openPlayPass": 42,
            "passesLeft": 5,
            "passesRight": 8,
            "successfulFinalThirdPasses": 12,
            "successfulOpenPlayPass": 38,
            "successfulPutThrough": 3,
            "totalBackZonePass": 14,
            "totalChippedPass": 4,
            "totalFinalThirdPasses": 18,
            "totalFlickOn": 5,
            "totalFwdZonePass": 22,
            "totalLayoffs": 6,
            "totalPass": 52,
            "totalThroughBall": 4,
            "putThrough": 3,

            # 슈팅/득점 관련
            "attBxCentre": 5,
            "attemptsIbox": 6,
            "attGoalHighRight": 2,
            "attHdMiss": 0,
            "attHdTotal": 1,
            "attIboxGoal": 3,
            "attIboxMiss": 3,
            "attLfGoal": 2,
            "attLfTotal": 4,
            "attMissLeft": 2,
            "attOpenplay": 4,
            "bigChanceMissed": 2,
            "Goals": 5,
            "goalsOpenplay": 4,
            "ontargetScoringAtt": 5,
            "shotOffTarget": 3,
            "totalScoringAtt": 8,
            "winningGoal": 1,

            # 수비/실점 관련
            "attemptsConcededIbox": 0,
            "attemptsConcededObox": 0,
            "goalsConceded": 0,
            "goalsConcededIbox": 0,

            # 볼 소유/드리블 관련
            "ballRecovery": 5,
            "carries": 28,
            "dispossessed": 4,
            "finalThirdEntries": 8,
            "penAreaEntries": 6,
            "possLostAll": 12,
            "possLostCtrl": 10,
            "possWonDef3rd": 2,
            "possWonMid3rd": 4,
            "progressiveCarries": 8,
            "Touches": 125,
            "touchesInFinalThird": 42,
            "touchesInOppBox": 18,
            "turnover": 3,
            "unsuccessfulTouch": 4,

            # 대인 플레이
            "challengeLost": 3,
            "duelLost": 5,
            "duelWon": 8,
            "timesTackled": 4,
            "totalContest": 6,
            "totalTackle": 2,
            "wonContest": 4,

            # 출전 관련
            "formationPlace": 10,
            "minsPlayed": 270,
            "totalSubOn": 0,
        },
    ],
}
