"""Basketball mock data for development and testing."""
from typing import Dict, List, Any

# Basketball games mock data
MOCK_BASKETBALL_GAMES: Dict[str, List[Dict[str, Any]]] = {
    "20251118_basketball": [
        {
            "game_id": "OT2025313104229",
            "compe": "basketball",
            "league_id": "OT313",
            "league_name": "NBA",
            "match_date": "20251118",
            "match_time": "09:00",
            "home_team_id": "OT31242",
            "away_team_id": "OT31238",
            "home_team_name": "클리블랜드",
            "away_team_name": "밀워키",
            "arena_name": "로킷 모기지 필드하우스",
            "home_score": 118,
            "away_score": 106,
            "state": "f"
        },
        {
            "game_id": "KBL2025118001",
            "compe": "basketball",
            "league_id": "KBL",
            "league_name": "KBL",
            "match_date": "20251118",
            "match_time": "19:00",
            "home_team_id": "KBL_DG",
            "away_team_id": "KBL_BS",
            "home_team_name": "대구가스공사",
            "away_team_name": "부산KCC",
            "arena_name": "대구실내체육관",
            "home_score": 93,
            "away_score": 94,
            "state": "b"
        },
        {
            "game_id": "WKBL2025118001",
            "compe": "basketball",
            "league_id": "WKBL",
            "league_name": "WKBL",
            "match_date": "20251118",
            "match_time": "17:00",
            "home_team_id": "WKBL_YI",
            "away_team_id": "WKBL_BC",
            "home_team_name": "용인 삼성생명 블루밍스",
            "away_team_name": "부천 하나원큐",
            "arena_name": "용인실내체육관",
            "home_score": 78,
            "away_score": 72,
            "state": "f"
        },
        {
            "game_id": "OT2025313104237",
            "compe": "basketball",
            "league_id": "OT313",
            "league_name": "NBA",
            "match_date": "20251118",
            "match_time": "11:30",
            "home_team_id": "OT31246",
            "away_team_id": "OT31239",
            "home_team_name": "보스턴",
            "away_team_name": "토론토",
            "arena_name": "TD 가든",
            "home_score": 108,
            "away_score": 96,
            "state": "f"
        },
    ],
}

# Basketball team stats mock data
MOCK_BASKETBALL_TEAM_STATS: Dict[str, List[Dict[str, Any]]] = {
    "OT2025313104237": [
        # Home team
        {
            "home_team_id": "OT31246",
            "home_team_name": "보스턴",
            "home_team_fgm_cn": 40,
            "home_team_fga_cn": 88,
            "home_team_fg_rt": "45.5",
            "home_team_tpm_cn": 18,
            "home_team_tpa_cn": 46,
            "home_team_tp_rt": "39.1",
            "home_team_ftm_cn": 10,
            "home_team_fta_cn": 12,
            "home_team_ft_rt": "83.3",
            "home_team_oreb_cn": 7,
            "home_team_dreb_cn": 37,
            "home_team_treb_cn": 44,
            "home_team_assist_cn": 24,
            "home_team_steal_cn": 8,
            "home_team_block_cn": 6,
            "home_team_turnover_cn": 13,
            "home_team_foul_cn": 12,
        },
        # Away team
        {
            "away_team_id": "OT31239",
            "away_team_name": "토론토",
            "away_team_fgm_cn": 37,
            "away_team_fga_cn": 90,
            "away_team_fg_rt": "41.1",
            "away_team_tpm_cn": 10,
            "away_team_tpa_cn": 34,
            "away_team_tp_rt": "29.4",
            "away_team_ftm_cn": 12,
            "away_team_fta_cn": 19,
            "away_team_ft_rt": "63.2",
            "away_team_oreb_cn": 11,
            "away_team_dreb_cn": 32,
            "away_team_treb_cn": 43,
            "away_team_assist_cn": 21,
            "away_team_steal_cn": 9,
            "away_team_block_cn": 4,
            "away_team_turnover_cn": 10,
            "away_team_foul_cn": 15,
        },
    ],
}

# Basketball lineup mock data (key: "{game_id}_{team_id}")
MOCK_BASKETBALL_LINEUP: Dict[str, List[Dict[str, Any]]] = {
    # Boston Celtics lineup for game OT2025313104237
    "OT2025313104237_OT31246": [
        {"player_id": "P001", "player_name": "테이텀", "back_no": "0", "pos_no": "21"},
        {"player_id": "P002", "player_name": "브라운", "back_no": "7", "pos_no": "22"},
        {"player_id": "P003", "player_name": "화이트", "back_no": "9", "pos_no": "23"},
        {"player_id": "P004", "player_name": "홀리데이", "back_no": "4", "pos_no": "24"},
        {"player_id": "P005", "player_name": "포르징기스", "back_no": "8", "pos_no": "25"},
        {"player_id": "P006", "player_name": "프릿차드", "back_no": "11", "pos_no": "5"},
        {"player_id": "P007", "player_name": "하우저", "back_no": "30", "pos_no": "5"},
    ],
    # Toronto Raptors lineup for game OT2025313104237
    "OT2025313104237_OT31239": [
        {"player_id": "P101", "player_name": "바렛", "back_no": "9", "pos_no": "21"},
        {"player_id": "P102", "player_name": "퀵리", "back_no": "1", "pos_no": "22"},
        {"player_id": "P103", "player_name": "반스", "back_no": "4", "pos_no": "23"},
        {"player_id": "P104", "player_name": "아누노비", "back_no": "3", "pos_no": "24"},
        {"player_id": "P105", "player_name": "푀틀", "back_no": "19", "pos_no": "25"},
        {"player_id": "P106", "player_name": "올리닉", "back_no": "13", "pos_no": "5"},
    ],
}

# Basketball player stats mock data
MOCK_BASKETBALL_PLAYER_STATS: Dict[str, List[Dict[str, Any]]] = {
    "OT2025313104237": [
        # Home team players (Boston Celtics)
        {
            "player_id": "P001",
            "player_name": "제이슨 테이텀",
            "team_id": "OT31246",
            "jersey_no": "0",
            "position": "SF",
            "play_time": "38:24",
            "tot_score": 33,
            "fgm_cn": 13,
            "fga_cn": 22,
            "fg_rt": "59.1",
            "tpm_cn": 5,
            "tpa_cn": 10,
            "tp_rt": "50.0",
            "ftm_cn": 2,
            "fta_cn": 4,
            "ft_rt": "50.0",
            "oreb_cn": 2,
            "dreb_cn": 10,
            "treb_cn": 12,
            "assist_cn": 9,
            "steal_cn": 2,
            "block_cn": 1,
            "turnover_cn": 4,
            "foul_cn": 2,
        },
        {
            "player_id": "P002",
            "player_name": "제이든 브라운",
            "team_id": "OT31246",
            "jersey_no": "7",
            "position": "SG",
            "play_time": "35:12",
            "tot_score": 28,
            "fgm_cn": 10,
            "fga_cn": 18,
            "fg_rt": "55.6",
            "tpm_cn": 4,
            "tpa_cn": 8,
            "tp_rt": "50.0",
            "ftm_cn": 4,
            "fta_cn": 5,
            "ft_rt": "80.0",
            "oreb_cn": 1,
            "dreb_cn": 6,
            "treb_cn": 7,
            "assist_cn": 5,
            "steal_cn": 1,
            "block_cn": 0,
            "turnover_cn": 2,
            "foul_cn": 3,
        },
        {
            "player_id": "P003",
            "player_name": "데릭 화이트",
            "team_id": "OT31246",
            "jersey_no": "9",
            "position": "PG",
            "play_time": "32:45",
            "tot_score": 18,
            "fgm_cn": 7,
            "fga_cn": 14,
            "fg_rt": "50.0",
            "tpm_cn": 3,
            "tpa_cn": 7,
            "tp_rt": "42.9",
            "ftm_cn": 1,
            "fta_cn": 1,
            "ft_rt": "100.0",
            "oreb_cn": 0,
            "dreb_cn": 4,
            "treb_cn": 4,
            "assist_cn": 6,
            "steal_cn": 2,
            "block_cn": 1,
            "turnover_cn": 1,
            "foul_cn": 2,
        },
        {
            "player_id": "P004",
            "player_name": "드류 홀리데이",
            "team_id": "OT31246",
            "jersey_no": "4",
            "position": "PG",
            "play_time": "30:18",
            "tot_score": 15,
            "fgm_cn": 5,
            "fga_cn": 12,
            "fg_rt": "41.7",
            "tpm_cn": 3,
            "tpa_cn": 6,
            "tp_rt": "50.0",
            "ftm_cn": 2,
            "fta_cn": 2,
            "ft_rt": "100.0",
            "oreb_cn": 1,
            "dreb_cn": 5,
            "treb_cn": 6,
            "assist_cn": 4,
            "steal_cn": 2,
            "block_cn": 0,
            "turnover_cn": 2,
            "foul_cn": 1,
        },
        {
            "player_id": "P005",
            "player_name": "크리스탑스 포르징기스",
            "team_id": "OT31246",
            "jersey_no": "8",
            "position": "C",
            "play_time": "28:30",
            "tot_score": 14,
            "fgm_cn": 5,
            "fga_cn": 10,
            "fg_rt": "50.0",
            "tpm_cn": 3,
            "tpa_cn": 5,
            "tp_rt": "60.0",
            "ftm_cn": 1,
            "fta_cn": 2,
            "ft_rt": "50.0",
            "oreb_cn": 3,
            "dreb_cn": 9,
            "treb_cn": 12,
            "assist_cn": 1,
            "steal_cn": 0,
            "block_cn": 4,
            "turnover_cn": 1,
            "foul_cn": 3,
        },
        # Away team players (Toronto Raptors)
        {
            "player_id": "P101",
            "player_name": "RJ 바렛",
            "team_id": "OT31239",
            "jersey_no": "9",
            "position": "SF",
            "play_time": "36:15",
            "tot_score": 22,
            "fgm_cn": 9,
            "fga_cn": 17,
            "fg_rt": "52.9",
            "tpm_cn": 2,
            "tpa_cn": 4,
            "tp_rt": "50.0",
            "ftm_cn": 2,
            "fta_cn": 4,
            "ft_rt": "50.0",
            "oreb_cn": 1,
            "dreb_cn": 4,
            "treb_cn": 5,
            "assist_cn": 2,
            "steal_cn": 1,
            "block_cn": 0,
            "turnover_cn": 2,
            "foul_cn": 3,
        },
        {
            "player_id": "P102",
            "player_name": "이매뉴엘 퀵리",
            "team_id": "OT31239",
            "jersey_no": "1",
            "position": "PG",
            "play_time": "34:42",
            "tot_score": 20,
            "fgm_cn": 8,
            "fga_cn": 16,
            "fg_rt": "50.0",
            "tpm_cn": 2,
            "tpa_cn": 6,
            "tp_rt": "33.3",
            "ftm_cn": 2,
            "fta_cn": 3,
            "ft_rt": "66.7",
            "oreb_cn": 0,
            "dreb_cn": 3,
            "treb_cn": 3,
            "assist_cn": 8,
            "steal_cn": 2,
            "block_cn": 0,
            "turnover_cn": 3,
            "foul_cn": 2,
        },
        {
            "player_id": "P103",
            "player_name": "스코티 반스",
            "team_id": "OT31239",
            "jersey_no": "4",
            "position": "PF",
            "play_time": "35:30",
            "tot_score": 19,
            "fgm_cn": 7,
            "fga_cn": 15,
            "fg_rt": "46.7",
            "tpm_cn": 1,
            "tpa_cn": 4,
            "tp_rt": "25.0",
            "ftm_cn": 4,
            "fta_cn": 5,
            "ft_rt": "80.0",
            "oreb_cn": 2,
            "dreb_cn": 8,
            "treb_cn": 10,
            "assist_cn": 6,
            "steal_cn": 1,
            "block_cn": 1,
            "turnover_cn": 2,
            "foul_cn": 4,
        },
        {
            "player_id": "P104",
            "player_name": "그래디 딕",
            "team_id": "OT31239",
            "jersey_no": "11",
            "position": "SG",
            "play_time": "28:20",
            "tot_score": 16,
            "fgm_cn": 6,
            "fga_cn": 13,
            "fg_rt": "46.2",
            "tpm_cn": 4,
            "tpa_cn": 9,
            "tp_rt": "44.4",
            "ftm_cn": 0,
            "fta_cn": 0,
            "ft_rt": "0.0",
            "oreb_cn": 0,
            "dreb_cn": 2,
            "treb_cn": 2,
            "assist_cn": 2,
            "steal_cn": 1,
            "block_cn": 0,
            "turnover_cn": 1,
            "foul_cn": 2,
        },
        {
            "player_id": "P105",
            "player_name": "야콥 푀틀",
            "team_id": "OT31239",
            "jersey_no": "19",
            "position": "C",
            "play_time": "26:45",
            "tot_score": 12,
            "fgm_cn": 5,
            "fga_cn": 8,
            "fg_rt": "62.5",
            "tpm_cn": 0,
            "tpa_cn": 0,
            "tp_rt": "0.0",
            "ftm_cn": 2,
            "fta_cn": 4,
            "ft_rt": "50.0",
            "oreb_cn": 4,
            "dreb_cn": 7,
            "treb_cn": 11,
            "assist_cn": 2,
            "steal_cn": 0,
            "block_cn": 2,
            "turnover_cn": 1,
            "foul_cn": 3,
        },
    ],
}

# Basketball team vs team comparison mock data (key: "{game_id}")
MOCK_BASKETBALL_TEAM_VS_LIST: Dict[str, Dict[str, Any]] = {
    # Boston vs Toronto game
    "OT2025313104237": {
        "home_team_id": "OT31246",
        "away_team_id": "OT31239",
        "home_group_sc": "EAST",
        "away_group_sc": "EAST",
        "home_team_rank": "4",
        "away_team_rank": "12",
        "home_team_all_w_cn": "15",
        "away_team_all_w_cn": "6",
        "home_team_all_l_cn": "11",
        "away_team_all_l_cn": "20",
        "home_team_5_w_cn": "3",
        "home_team_5_l_cn": "2",
        "away_team_5_w_cn": "1",
        "away_team_5_l_cn": "4",
        "home_team_all_wra_rt": ".577",
        "away_team_all_wra_rt": ".231",
        "home_team_h_wra_rt": ".667",
        "away_team_h_wra_rt": ".308",
        "home_team_a_wra_rt": ".500",
        "away_team_a_wra_rt": ".154",
        "home_team_all_r_score": "117.2",
        "away_team_all_r_score": "108.5",
        "home_team_all_l_score": "112.8",
        "away_team_all_l_score": "116.3",
        "home_team_fgp_rt": "47.5",
        "away_team_fgp_rt": "44.2",
        "home_team_p3_rt": "38.1",
        "away_team_p3_rt": "33.5",
        "home_team_assist_cn": "26.4",
        "away_team_assist_cn": "22.1",
        "home_team_turnover_cn": "13.2",
        "away_team_turnover_cn": "14.8",
        "home_team_steal_cn": "7.5",
        "away_team_steal_cn": "6.2",
        "home_team_reb_cn": "44.8",
        "away_team_reb_cn": "41.3",
        "home_team_blk_avg": "5.2",
        "away_team_blk_avg": "4.1",
        "home_league_id": "OT313",
    },
    # Cleveland vs Milwaukee game
    "OT2025313104229": {
        "home_team_id": "OT31242",
        "away_team_id": "OT31238",
        "home_group_sc": "EAST",
        "away_group_sc": "EAST",
        "home_team_rank": "1",
        "away_team_rank": "5",
        "home_team_all_w_cn": "21",
        "away_team_all_w_cn": "14",
        "home_team_all_l_cn": "5",
        "away_team_all_l_cn": "11",
        "home_team_5_w_cn": "4",
        "home_team_5_l_cn": "1",
        "away_team_5_w_cn": "2",
        "away_team_5_l_cn": "3",
        "home_team_all_wra_rt": ".808",
        "away_team_all_wra_rt": ".560",
        "home_team_h_wra_rt": ".846",
        "away_team_h_wra_rt": ".615",
        "home_team_a_wra_rt": ".769",
        "away_team_a_wra_rt": ".500",
        "home_team_all_r_score": "121.5",
        "away_team_all_r_score": "115.8",
        "home_team_all_l_score": "108.2",
        "away_team_all_l_score": "114.5",
        "home_team_fgp_rt": "49.2",
        "away_team_fgp_rt": "46.8",
        "home_team_p3_rt": "39.5",
        "away_team_p3_rt": "36.2",
        "home_team_assist_cn": "28.1",
        "away_team_assist_cn": "24.5",
        "home_team_turnover_cn": "12.5",
        "away_team_turnover_cn": "13.8",
        "home_team_steal_cn": "8.2",
        "away_team_steal_cn": "6.8",
        "home_team_reb_cn": "46.2",
        "away_team_reb_cn": "43.5",
        "home_team_blk_avg": "5.8",
        "away_team_blk_avg": "4.5",
        "home_league_id": "OT313",
    },
}

# Basketball team rankings mock data (key: "{season_id}_{league_id}")
MOCK_BASKETBALL_TEAM_RANK: Dict[str, List[Dict[str, Any]]] = {
    # NBA 2025 season rankings
    "2025_OT313": [
        # Eastern Conference
        {"group": "EAST", "rank": 1, "team_id": "OT31237", "team_name": "클리블랜드", "games": 26, "wins": "21", "losses": "5", "win_rate": ".808", "games_behind": "0.0"},
        {"group": "EAST", "rank": 2, "team_id": "OT31264", "team_name": "인디애나", "games": 25, "wins": "18", "losses": "7", "win_rate": ".720", "games_behind": "2.5"},
        {"group": "EAST", "rank": 3, "team_id": "OT31240", "team_name": "올랜도", "games": 27, "wins": "16", "losses": "11", "win_rate": ".593", "games_behind": "5.5"},
        {"group": "EAST", "rank": 4, "team_id": "OT31246", "team_name": "보스턴", "games": 26, "wins": "15", "losses": "11", "win_rate": ".577", "games_behind": "6.0"},
        {"group": "EAST", "rank": 5, "team_id": "OT31239", "team_name": "토론토", "games": 26, "wins": "6", "losses": "20", "win_rate": ".231", "games_behind": "15.0"},
        # Western Conference
        {"group": "WEST", "rank": 1, "team_id": "OT31255", "team_name": "오클라호마시티", "games": 26, "wins": "24", "losses": "2", "win_rate": ".923", "games_behind": "0.0"},
        {"group": "WEST", "rank": 2, "team_id": "OT31257", "team_name": "멤피스", "games": 25, "wins": "19", "losses": "6", "win_rate": ".760", "games_behind": "4.5"},
        {"group": "WEST", "rank": 3, "team_id": "OT31252", "team_name": "휴스턴", "games": 25, "wins": "18", "losses": "7", "win_rate": ".720", "games_behind": "5.5"},
        {"group": "WEST", "rank": 4, "team_id": "OT31254", "team_name": "LA 레이커스", "games": 25, "wins": "18", "losses": "7", "win_rate": ".720", "games_behind": "5.5"},
        {"group": "WEST", "rank": 5, "team_id": "OT31250", "team_name": "덴버", "games": 23, "wins": "16", "losses": "7", "win_rate": ".696", "games_behind": "6.5"},
    ],
}
