"""Basketball mock data for development and testing."""
from typing import Dict, List, Any

# Basketball games mock data
MOCK_BASKETBALL_GAMES: Dict[str, List[Dict[str, Any]]] = {
    "20251118_basketball": [
        {
            "game_id": "OT2025313104229",
            "compe": "basketball",
            "league_id": "OT313",
            "league_name": "NBA",
            "match_date": "20251118",
            "match_time": "09:00",
            "home_team_id": "OT31242",
            "away_team_id": "OT31238",
            "home_team_name": "클리블랜드",
            "away_team_name": "밀워키",
            "arena_name": "로킷 모기지 필드하우스",
            "home_score": 118,
            "away_score": 106,
            "state": "f"
        },
        {
            "game_id": "KBL2025118001",
            "compe": "basketball",
            "league_id": "KBL",
            "league_name": "KBL",
            "match_date": "20251118",
            "match_time": "19:00",
            "home_team_id": "KBL_DG",
            "away_team_id": "KBL_BS",
            "home_team_name": "대구가스공사",
            "away_team_name": "부산KCC",
            "arena_name": "대구실내체육관",
            "home_score": 93,
            "away_score": 94,
            "state": "b"
        },
        {
            "game_id": "WKBL2025118001",
            "compe": "basketball",
            "league_id": "WKBL",
            "league_name": "WKBL",
            "match_date": "20251118",
            "match_time": "17:00",
            "home_team_id": "WKBL_YI",
            "away_team_id": "WKBL_BC",
            "home_team_name": "용인 삼성생명 블루밍스",
            "away_team_name": "부천 하나원큐",
            "arena_name": "용인실내체육관",
            "home_score": 78,
            "away_score": 72,
            "state": "f"
        },
        {
            "game_id": "OT2025313104237",
            "compe": "basketball",
            "league_id": "OT313",
            "league_name": "NBA",
            "match_date": "20251118",
            "match_time": "11:30",
            "home_team_id": "OT31246",
            "away_team_id": "OT31239",
            "home_team_name": "보스턴",
            "away_team_name": "토론토",
            "arena_name": "TD 가든",
            "home_score": 108,
            "away_score": 96,
            "state": "f"
        },
    ],
}

# Basketball team stats mock data
MOCK_BASKETBALL_TEAM_STATS: Dict[str, List[Dict[str, Any]]] = {
    "OT2025313104237": [
        # Home team
        {
            "home_team_id": "OT31246",
            "home_team_name": "보스턴",
            "home_team_fgm_cn": 40,
            "home_team_fga_cn": 88,
            "home_team_fg_rt": "45.5",
            "home_team_tpm_cn": 18,
            "home_team_tpa_cn": 46,
            "home_team_tp_rt": "39.1",
            "home_team_ftm_cn": 10,
            "home_team_fta_cn": 12,
            "home_team_ft_rt": "83.3",
            "home_team_oreb_cn": 7,
            "home_team_dreb_cn": 37,
            "home_team_treb_cn": 44,
            "home_team_assist_cn": 24,
            "home_team_steal_cn": 8,
            "home_team_block_cn": 6,
            "home_team_turnover_cn": 13,
            "home_team_foul_cn": 12,
        },
        # Away team
        {
            "away_team_id": "OT31239",
            "away_team_name": "토론토",
            "away_team_fgm_cn": 37,
            "away_team_fga_cn": 90,
            "away_team_fg_rt": "41.1",
            "away_team_tpm_cn": 10,
            "away_team_tpa_cn": 34,
            "away_team_tp_rt": "29.4",
            "away_team_ftm_cn": 12,
            "away_team_fta_cn": 19,
            "away_team_ft_rt": "63.2",
            "away_team_oreb_cn": 11,
            "away_team_dreb_cn": 32,
            "away_team_treb_cn": 43,
            "away_team_assist_cn": 21,
            "away_team_steal_cn": 9,
            "away_team_block_cn": 4,
            "away_team_turnover_cn": 10,
            "away_team_foul_cn": 15,
        },
    ],
}

# Basketball player stats mock data
MOCK_BASKETBALL_PLAYER_STATS: Dict[str, List[Dict[str, Any]]] = {
    "OT2025313104237": [
        # Home team players
        {
            "player_id": "P001",
            "player_name": "제이슨 테이텀",
            "team_id": "OT31246",
            "jersey_no": "0",
            "tot_score": 33,
            "fgm_cn": 13,
            "fga_cn": 22,
            "fg_rt": "59.1",
            "tpm_cn": 5,
            "tpa_cn": 10,
            "tp_rt": "50.0",
            "ftm_cn": 2,
            "fta_cn": 4,
            "ft_rt": "50.0",
            "oreb_cn": 2,
            "dreb_cn": 10,
            "treb_cn": 12,
            "assist_cn": 9,
            "steal_cn": 2,
            "block_cn": 1,
            "turnover_cn": 4,
            "foul_cn": 2,
        },
        # Away team players
        {
            "player_id": "P101",
            "player_name": "RJ 바렛",
            "team_id": "OT31239",
            "jersey_no": "9",
            "tot_score": 22,
            "fgm_cn": 9,
            "fga_cn": 17,
            "fg_rt": "52.9",
            "tpm_cn": 2,
            "tpa_cn": 4,
            "tp_rt": "50.0",
            "ftm_cn": 2,
            "fta_cn": 4,
            "ft_rt": "50.0",
            "oreb_cn": 1,
            "dreb_cn": 4,
            "treb_cn": 5,
            "assist_cn": 2,
            "steal_cn": 1,
            "block_cn": 0,
            "turnover_cn": 2,
            "foul_cn": 3,
        },
    ],
}
