"""Baseball mock data for testing."""
from typing import Dict, Any, List

# Game list mock (gameList API)
MOCK_BASEBALL_GAMES: Dict[str, List[Dict[str, Any]]] = {
    "20250502_baseball": [
        {
            "game_id": "20250502KTSS0",
            "league_id": "11",
            "league_name": "KBO리그",
            "match_date": "20250502",
            "match_time": "18:30",
            "home_team_id": "SS",
            "home_team_name": "삼성",
            "away_team_id": "KT",
            "away_team_name": "KT",
            "home_score": "4",
            "away_score": "2",
            "state": "F",
            "arena_name": "대구삼성라이온즈파크",
            "compe": "2",
        },
        {
            "game_id": "20250502LGHH0",
            "league_id": "11",
            "league_name": "KBO리그",
            "match_date": "20250502",
            "match_time": "18:30",
            "home_team_id": "HH",
            "home_team_name": "한화",
            "away_team_id": "LG",
            "away_team_name": "LG",
            "home_score": "0",
            "away_score": "0",
            "state": "B",
            "arena_name": "한화생명이글스파크",
            "compe": "2",
        },
    ]
}

# Game detail mock (baseballGameTotalInfo API)
MOCK_BASEBALL_GAME_TOTAL_INFO: Dict[str, Dict[str, Any]] = {
    "20250502KTSS0": {
        "gameInfo": {
            "game_id": "20250502KTSS0",
            "league_id": "11",
            "league_name": "KBO리그",
            "match_date": "20250502",
            "match_time": "18:30",
            "home_team_id": "SS",
            "home_team_name": "삼성",
            "away_team_id": "KT",
            "away_team_name": "KT",
            "home_score": "4",
            "away_score": "2",
            "state": "F",
            "arena_name": "대구삼성라이온즈파크",
            "home_starter_name": "원태인",
            "away_starter_name": "엄상백",
        },
        "homeTeamInfo": {
            "home_team_rank_no": "3",
            "home_team_w_cn": "18",
            "home_team_d_cn": "0",
            "home_team_l_cn": "14",
            "home_team_wra_rt": ".563",
            "home_team_win_gap_va": "3.5",
            "home_team_hra_rt": ".281",
        },
        "awayTeamInfo": {
            "away_team_rank_no": "6",
            "away_team_w_cn": "14",
            "away_team_d_cn": "1",
            "away_team_l_cn": "17",
            "away_team_wra_rt": ".452",
            "away_team_win_gap_va": "7.0",
            "away_team_hra_rt": ".263",
        },
        "totalStatInfo": {
            "home_team_score_cn": "4",
            "away_team_score_cn": "2",
            "home_team_hit_cn": "10",
            "away_team_hit_cn": "6",
            "home_team_hr_cn": "1",
            "away_team_hr_cn": "0",
            "home_team_bbhp_cn": "3",
            "away_team_bbhp_cn": "2",
            "home_team_sb_cn": "1",
            "away_team_sb_cn": "0",
            "home_team_err_cn": "0",
            "away_team_err_cn": "1",
            "home_team_h_hra": ".294",
            "away_team_h_hra": ".231",
            "home_team_p_era": "2.25",
            "away_team_p_era": "3.60",
        },
        "inningScore": [
            {"inning_no": "1", "home_score": "0", "away_score": "0"},
            {"inning_no": "2", "home_score": "2", "away_score": "0"},
            {"inning_no": "3", "home_score": "0", "away_score": "1"},
            {"inning_no": "4", "home_score": "0", "away_score": "0"},
            {"inning_no": "5", "home_score": "0", "away_score": "0"},
            {"inning_no": "6", "home_score": "1", "away_score": "0"},
            {"inning_no": "7", "home_score": "0", "away_score": "1"},
            {"inning_no": "8", "home_score": "1", "away_score": "0"},
            {"inning_no": "9", "home_score": "X", "away_score": "0"},
        ],
        "vsInfo": {
            "home_team_vs_w_cn": "7",
            "home_team_vs_l_cn": "5",
            "home_team_vs_d_cn": "0",
            "away_team_vs_w_cn": "5",
            "away_team_vs_l_cn": "7",
            "away_team_vs_d_cn": "0",
            "home_team_5_w_cn": "3",
            "home_team_5_l_cn": "2",
            "home_team_5_wdl": "W,L,W,W,L",
            "away_team_5_w_cn": "2",
            "away_team_5_l_cn": "3",
            "away_team_5_wdl": "L,W,L,L,W",
        },
        "pitcherStat": {
            "home": [
                {
                    "turn_no": "1",
                    "player_name": "원태인",
                    "w_yn": "Y",
                    "l_yn": "N",
                    "s_yn": "N",
                    "h_yn": "N",
                    "bs_yn": "N",
                    "pitch_inning": "7.0",
                    "pit_cn": "98",
                    "hit_cn": "5",
                    "kk_cn": "8",
                    "r_cn": "2",
                    "er_cn": "2",
                    "era_rt": "2.57",
                    "whip_rt": "1.14",
                },
                {
                    "turn_no": "2",
                    "player_name": "김태훈",
                    "w_yn": "N",
                    "l_yn": "N",
                    "s_yn": "N",
                    "h_yn": "Y",
                    "bs_yn": "N",
                    "pitch_inning": "1.0",
                    "pit_cn": "12",
                    "hit_cn": "1",
                    "kk_cn": "1",
                    "r_cn": "0",
                    "er_cn": "0",
                    "era_rt": "1.80",
                    "whip_rt": "0.90",
                },
                {
                    "turn_no": "3",
                    "player_name": "이승현",
                    "w_yn": "N",
                    "l_yn": "N",
                    "s_yn": "Y",
                    "h_yn": "N",
                    "bs_yn": "N",
                    "pitch_inning": "1.0",
                    "pit_cn": "15",
                    "hit_cn": "0",
                    "kk_cn": "2",
                    "r_cn": "0",
                    "er_cn": "0",
                    "era_rt": "2.08",
                    "whip_rt": "0.77",
                },
            ],
            "away": [
                {
                    "turn_no": "1",
                    "player_name": "엄상백",
                    "w_yn": "N",
                    "l_yn": "Y",
                    "s_yn": "N",
                    "h_yn": "N",
                    "bs_yn": "N",
                    "pitch_inning": "5.1",
                    "pit_cn": "92",
                    "hit_cn": "7",
                    "kk_cn": "4",
                    "r_cn": "3",
                    "er_cn": "3",
                    "era_rt": "4.50",
                    "whip_rt": "1.50",
                },
                {
                    "turn_no": "2",
                    "player_name": "박영현",
                    "w_yn": "N",
                    "l_yn": "N",
                    "s_yn": "N",
                    "h_yn": "N",
                    "bs_yn": "N",
                    "pitch_inning": "2.2",
                    "pit_cn": "38",
                    "hit_cn": "3",
                    "kk_cn": "3",
                    "r_cn": "1",
                    "er_cn": "1",
                    "era_rt": "3.15",
                    "whip_rt": "1.28",
                },
                {
                    "turn_no": "3",
                    "player_name": "김민수",
                    "w_yn": "N",
                    "l_yn": "N",
                    "s_yn": "N",
                    "h_yn": "N",
                    "bs_yn": "N",
                    "pitch_inning": "1.0",
                    "pit_cn": "17",
                    "hit_cn": "0",
                    "kk_cn": "1",
                    "r_cn": "0",
                    "er_cn": "0",
                    "era_rt": "2.89",
                    "whip_rt": "0.96",
                },
            ],
        },
        "batterStat": {
            "home": [
                {
                    "bat_order_no": "1",
                    "player_name": "이재현",
                    "pos_sc": "2B",
                    "ab_cn": "4",
                    "hit_cn": "2",
                    "hr_cn": "0",
                    "rbi_cn": "1",
                    "bb_cn": "0",
                    "kk_cn": "1",
                    "hra_rt": ".312",
                    "obp_rt": ".380",
                    "ops_rt": ".856",
                },
                {
                    "bat_order_no": "2",
                    "player_name": "김헌곤",
                    "pos_sc": "RF",
                    "ab_cn": "4",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "1",
                    "kk_cn": "2",
                    "hra_rt": ".290",
                    "obp_rt": ".365",
                    "ops_rt": ".810",
                },
                {
                    "bat_order_no": "3",
                    "player_name": "구자욱",
                    "pos_sc": "LF",
                    "ab_cn": "4",
                    "hit_cn": "3",
                    "hr_cn": "1",
                    "rbi_cn": "2",
                    "bb_cn": "0",
                    "kk_cn": "0",
                    "hra_rt": ".325",
                    "obp_rt": ".395",
                    "ops_rt": ".975",
                },
                {
                    "bat_order_no": "4",
                    "player_name": "디아즈",
                    "pos_sc": "1B",
                    "ab_cn": "4",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "1",
                    "bb_cn": "1",
                    "kk_cn": "1",
                    "hra_rt": ".280",
                    "obp_rt": ".355",
                    "ops_rt": ".820",
                },
                {
                    "bat_order_no": "5",
                    "player_name": "강민호",
                    "pos_sc": "C",
                    "ab_cn": "3",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "1",
                    "kk_cn": "0",
                    "hra_rt": ".267",
                    "obp_rt": ".340",
                    "ops_rt": ".762",
                },
                {
                    "bat_order_no": "6",
                    "player_name": "김지찬",
                    "pos_sc": "CF",
                    "ab_cn": "4",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "2",
                    "hra_rt": ".245",
                    "obp_rt": ".310",
                    "ops_rt": ".700",
                },
                {
                    "bat_order_no": "7",
                    "player_name": "박병호",
                    "pos_sc": "DH",
                    "ab_cn": "3",
                    "hit_cn": "0",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "1",
                    "kk_cn": "2",
                    "hra_rt": ".222",
                    "obp_rt": ".305",
                    "ops_rt": ".680",
                },
                {
                    "bat_order_no": "8",
                    "player_name": "김성윤",
                    "pos_sc": "SS",
                    "ab_cn": "3",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "1",
                    "hra_rt": ".258",
                    "obp_rt": ".315",
                    "ops_rt": ".715",
                },
                {
                    "bat_order_no": "9",
                    "player_name": "이원석",
                    "pos_sc": "3B",
                    "ab_cn": "3",
                    "hit_cn": "0",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "1",
                    "hra_rt": ".235",
                    "obp_rt": ".290",
                    "ops_rt": ".655",
                },
            ],
            "away": [
                {
                    "bat_order_no": "1",
                    "player_name": "황재균",
                    "pos_sc": "3B",
                    "ab_cn": "4",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "1",
                    "hra_rt": ".272",
                    "obp_rt": ".340",
                    "ops_rt": ".755",
                },
                {
                    "bat_order_no": "2",
                    "player_name": "배정대",
                    "pos_sc": "RF",
                    "ab_cn": "4",
                    "hit_cn": "2",
                    "hr_cn": "0",
                    "rbi_cn": "1",
                    "bb_cn": "0",
                    "kk_cn": "0",
                    "hra_rt": ".298",
                    "obp_rt": ".355",
                    "ops_rt": ".820",
                },
                {
                    "bat_order_no": "3",
                    "player_name": "강백호",
                    "pos_sc": "1B",
                    "ab_cn": "3",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "1",
                    "bb_cn": "1",
                    "kk_cn": "1",
                    "hra_rt": ".310",
                    "obp_rt": ".390",
                    "ops_rt": ".880",
                },
                {
                    "bat_order_no": "4",
                    "player_name": "로하스",
                    "pos_sc": "LF",
                    "ab_cn": "4",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "2",
                    "hra_rt": ".285",
                    "obp_rt": ".345",
                    "ops_rt": ".795",
                },
                {
                    "bat_order_no": "5",
                    "player_name": "장성우",
                    "pos_sc": "C",
                    "ab_cn": "4",
                    "hit_cn": "0",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "2",
                    "hra_rt": ".230",
                    "obp_rt": ".295",
                    "ops_rt": ".660",
                },
                {
                    "bat_order_no": "6",
                    "player_name": "김민혁",
                    "pos_sc": "CF",
                    "ab_cn": "3",
                    "hit_cn": "1",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "1",
                    "kk_cn": "0",
                    "hra_rt": ".255",
                    "obp_rt": ".325",
                    "ops_rt": ".720",
                },
                {
                    "bat_order_no": "7",
                    "player_name": "심우준",
                    "pos_sc": "SS",
                    "ab_cn": "4",
                    "hit_cn": "0",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "3",
                    "hra_rt": ".210",
                    "obp_rt": ".265",
                    "ops_rt": ".580",
                },
                {
                    "bat_order_no": "8",
                    "player_name": "박경수",
                    "pos_sc": "DH",
                    "ab_cn": "3",
                    "hit_cn": "0",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "1",
                    "hra_rt": ".198",
                    "obp_rt": ".255",
                    "ops_rt": ".555",
                },
                {
                    "bat_order_no": "9",
                    "player_name": "오윤석",
                    "pos_sc": "2B",
                    "ab_cn": "3",
                    "hit_cn": "0",
                    "hr_cn": "0",
                    "rbi_cn": "0",
                    "bb_cn": "0",
                    "kk_cn": "2",
                    "hra_rt": ".215",
                    "obp_rt": ".270",
                    "ops_rt": ".600",
                },
            ],
        },
    },
    "20250502LGHH0": {
        "gameInfo": {
            "game_id": "20250502LGHH0",
            "league_id": "11",
            "league_name": "KBO리그",
            "match_date": "20250502",
            "match_time": "18:30",
            "home_team_id": "HH",
            "home_team_name": "한화",
            "away_team_id": "LG",
            "away_team_name": "LG",
            "home_score": "0",
            "away_score": "0",
            "state": "B",
            "arena_name": "한화생명이글스파크",
            "home_starter_name": "류현진",
            "away_starter_name": "임찬규",
        },
        "homeTeamInfo": {
            "home_team_rank_no": "5",
            "home_team_w_cn": "16",
            "home_team_d_cn": "0",
            "home_team_l_cn": "16",
            "home_team_wra_rt": ".500",
            "home_team_win_gap_va": "5.5",
            "home_team_hra_rt": ".270",
        },
        "awayTeamInfo": {
            "away_team_rank_no": "2",
            "away_team_w_cn": "20",
            "away_team_d_cn": "0",
            "away_team_l_cn": "12",
            "away_team_wra_rt": ".625",
            "away_team_win_gap_va": "0.0",
            "away_team_hra_rt": ".285",
        },
        "totalStatInfo": {},
        "inningScore": [],
        "vsInfo": {
            "home_team_vs_w_cn": "4",
            "home_team_vs_l_cn": "8",
            "home_team_vs_d_cn": "0",
            "away_team_vs_w_cn": "8",
            "away_team_vs_l_cn": "4",
            "away_team_vs_d_cn": "0",
            "home_team_5_w_cn": "2",
            "home_team_5_l_cn": "3",
            "home_team_5_wdl": "L,W,W,L,L",
            "away_team_5_w_cn": "4",
            "away_team_5_l_cn": "1",
            "away_team_5_wdl": "W,W,L,W,W",
        },
        "pitcherStat": {"home": [], "away": []},
        "batterStat": {"home": [], "away": []},
    },
}
